import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "AI Mock Interview - Practice with AI Interviewers | HireOG",
  description: "Practice AI-based mock interviews with professional AI interviewers from top tech companies. Get personalized feedback, video recording, and comprehensive analysis. Perfect for frontend, backend, product manager, and HR interview preparation.",
  keywords: [
    "ai based mock interview",
    "ai interview",
    "ai mock interview",
    "artificial intelligence interview",
    "ai interview practice",
    "ai interview questions",
    "ai interview platform",
    "ai interview simulator",
    "ai interview prep",
    "ai interview training",
    "ai interview coach",
    "ai interview assistant",
    "ai interview bot",
    "ai interview system",
    "ai interview software",
    "ai interview tool",
    "ai interview app",
    "ai interview website",
    "ai interview service",
    "ai interview solution",
    "mock interview ai",
    "ai interview practice online",
    "ai interview questions and answers",
    "ai interview preparation",
    "ai interview training platform",
    "ai interview coaching",
    "ai interview feedback",
    "ai interview analysis",
    "ai interview scoring",
    "ai interview evaluation",
    "ai interview assessment",
    "ai interview testing",
    "ai interview simulation",
    "ai interview experience",
    "ai interview session",
    "ai interview recording",
    "ai interview video",
    "ai interview audio",
    "ai interview voice",
    "ai interview speech",
    "ai interview conversation",
    "ai interview dialogue",
    "ai interview interaction",
    "ai interview communication",
    "ai interview skills",
    "ai interview techniques",
    "ai interview strategies",
    "ai interview tips",
    "ai interview best practices",
    "ai interview guidelines",
    "ai interview standards",
    "ai interview quality",
    "ai interview performance",
    "ai interview results",
    "ai interview outcomes",
    "ai interview success",
    "ai interview improvement",
    "ai interview development",
    "ai interview growth",
    "ai interview advancement",
    "ai interview progress",
    "ai interview achievement",
    "ai interview accomplishment",
    "ai interview mastery",
    "ai interview expertise",
    "ai interview proficiency",
    "ai interview competency",
    "ai interview capability",
    "ai interview talent",
    "ai interview skill",
    "ai interview ability",
    "ai interview potential",
    "ai interview opportunity",
    "ai interview chance",
    "ai interview possibility",
    "ai interview option",
    "ai interview choice",
    "ai interview selection",
    "ai interview preference",
    "ai interview recommendation",
    "ai interview suggestion",
    "ai interview advice",
    "ai interview guidance",
    "ai interview support",
    "ai interview help",
    "ai interview assistance",
    "ai interview service",
    "ai interview solution",
    "ai interview platform",
    "ai interview system",
    "ai interview tool",
    "ai interview software",
    "ai interview application",
    "ai interview program",
    "ai interview website",
    "ai interview online",
    "ai interview digital",
    "ai interview virtual",
    "ai interview remote",
    "ai interview distance",
    "ai interview global",
    "ai interview worldwide",
    "ai interview international",
    "ai interview universal",
    "ai interview comprehensive",
    "ai interview complete",
    "ai interview full",
    "ai interview total",
    "ai interview entire",
    "ai interview whole",
    "ai interview all",
    "ai interview everything",
    "ai interview anything",
    "ai interview something",
    "ai interview nothing",
    "ai interview anything",
    "ai interview everything",
    "ai interview all",
    "ai interview whole",
    "ai interview total",
    "ai interview complete",
    "ai interview comprehensive",
    "ai interview universal",
    "ai interview worldwide",
    "ai interview global",
    "ai interview international",
    "ai interview remote",
    "ai interview virtual",
    "ai interview digital",
    "ai interview online",
    "ai interview website",
    "ai interview application",
    "ai interview program",
    "ai interview software",
    "ai interview tool",
    "ai interview system",
    "ai interview platform",
    "ai interview solution",
    "ai interview service",
    "ai interview assistance",
    "ai interview help",
    "ai interview support",
    "ai interview guidance",
    "ai interview advice",
    "ai interview suggestion",
    "ai interview recommendation",
    "ai interview choice",
    "ai interview selection",
    "ai interview preference",
    "ai interview option",
    "ai interview possibility",
    "ai interview chance",
    "ai interview opportunity",
    "ai interview potential",
    "ai interview ability",
    "ai interview skill",
    "ai interview talent",
    "ai interview capability",
    "ai interview competency",
    "ai interview proficiency",
    "ai interview expertise",
    "ai interview mastery",
    "ai interview accomplishment",
    "ai interview achievement",
    "ai interview progress",
    "ai interview advancement",
    "ai interview development",
    "ai interview growth",
    "ai interview improvement",
    "ai interview success",
    "ai interview outcomes",
    "ai interview results",
    "ai interview performance",
    "ai interview quality",
    "ai interview standards",
    "ai interview guidelines",
    "ai interview best practices",
    "ai interview tips",
    "ai interview strategies",
    "ai interview techniques",
    "ai interview skills",
    "ai interview communication",
    "ai interview interaction",
    "ai interview dialogue",
    "ai interview conversation",
    "ai interview speech",
    "ai interview voice",
    "ai interview audio",
    "ai interview video",
    "ai interview recording",
    "ai interview session",
    "ai interview experience",
    "ai interview simulation",
    "ai interview testing",
    "ai interview assessment",
    "ai interview evaluation",
    "ai interview scoring",
    "ai interview analysis",
    "ai interview feedback",
    "ai interview coaching",
    "ai interview training platform",
    "ai interview preparation",
    "ai interview questions and answers",
    "ai interview practice online",
    "mock interview ai",
    "ai interview solution",
    "ai interview service",
    "ai interview website",
    "ai interview app",
    "ai interview tool",
    "ai interview software",
    "ai interview system",
    "ai interview platform",
    "ai interview simulator",
    "ai interview prep",
    "ai interview training",
    "ai interview coach",
    "ai interview assistant",
    "ai interview bot",
    "ai interview questions",
    "ai interview practice",
    "artificial intelligence interview",
    "ai mock interview",
    "ai interview",
    "ai based mock interview"
  ],
  openGraph: {
    title: "AI Mock Interview - Practice with AI Interviewers | HireOG",
    description: "Practice AI-based mock interviews with professional AI interviewers from top tech companies. Get personalized feedback, video recording, and comprehensive analysis.",
    url: "https://hireog.com/ai-interview",
    siteName: "HireOG",
    images: [
      {
        url: "https://hireog.com/og-ai-interview.jpg",
        width: 1200,
        height: 630,
        alt: "AI Mock Interview Platform - HireOG",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "AI Mock Interview - Practice with AI Interviewers | HireOG",
    description: "Practice AI-based mock interviews with professional AI interviewers from top tech companies. Get personalized feedback, video recording, and comprehensive analysis.",
    images: ["https://hireog.com/og-ai-interview.jpg"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  alternates: {
    canonical: "https://hireog.com/ai-interview",
  },
};

export default function AIInterviewLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
